// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/contractor-websites": {
    params: {};
  };
  "/seo-for-contractors": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/pricing" | "/contact" | "/contractor-websites" | "/seo-for-contractors" | "/portfolio";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/pricing.jsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "./routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "./routes/contractor-websites.jsx": {
    id: "routes/contractor-websites";
    page: "/contractor-websites";
  };
  "./routes/seo-for-contractors.jsx": {
    id: "routes/seo-for-contractors";
    page: "/seo-for-contractors";
  };
  "./routes/portfolio.jsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "routes/home": typeof import("./src/./routes/home.jsx");
  "routes/pricing": typeof import("./src/./routes/pricing.jsx");
  "routes/contact": typeof import("./src/./routes/contact.jsx");
  "routes/contractor-websites": typeof import("./src/./routes/contractor-websites.jsx");
  "routes/seo-for-contractors": typeof import("./src/./routes/seo-for-contractors.jsx");
  "routes/portfolio": typeof import("./src/./routes/portfolio.jsx");
};